app/urls.py
from django.urls import path
from . import views


app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('passwordgenerator', views.password, name='password')
]

forother/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render
from random import choice


# Create your views here.

def index(requests):
    context = {
        'hello': 'Hello To WebApp for Generator Password'
    }
    return render(requests, 'app/index.html', context)


def password(requests):
    ''' character for generate password'''
    characterOfPassword = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefjssdcngavx1234567890@#!~*&'
    passGenerated = ''
    for i in range(8):
        passGenerated += choice(characterOfPassword)
    context = {
        'password': passGenerated,
    }

    return render(requests, 'app/passwordgenrator.html', context)

app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ hello }}</title>
</head>
<body>
    <h1>Hello To WebApp for Generator Password</h1>
    <br>
    <br>
    <a href="{% url 'app:password' %}"><button>go to generate password</button></a>
</body>
</html>

app/templates/app/passwordgenrator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>generate password</title>
</head>
<body>
    <h1>generate password</h1><br>
    <h2>your password : </h2><br>
    <h3>{{ password }}</h3>
    <br>
    <a href="{% url 'app:password' %}"><button>change password generated</button></a>
    <br>
    <br>
    <br>
    <a href="{% url 'app:index' %}"><button>back to homepage</button></a>
</body>
</html>